update pre-commit3

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,19 +1,17 @@
 #!/bin/sh
-# Exit if no files are staged for commit
+
 FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
-# Prettify all selected files
 echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
 echo -e "\nValidating Javascript & Typescript with eslint:"
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx{0,1}$|\.tsx{0,1}$")
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
+
 if [ -n "$STAGED_FILES" ]; then
-  # Run ESLint and capture the output
   ESLINT_OUTPUT=$(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --format json)
   
-  # Check if there are any errors
   if echo "$ESLINT_OUTPUT" | grep -q '"errorCount": [1-9]'; then
     echo -e "ESLint found errors, aborting commit."
     echo "$ESLINT_OUTPUT" | ./node_modules/.bin/eslint-formatter-friendly
@@ -23,17 +21,48 @@ if [ -n "$STAGED_FILES" ]; then
   fi
 fi
 
-# Validate TypeScript compilation
 echo -e "\nValidating TypeScript compilation:"
-./node_modules/.bin/tsc --noEmit
-if [ $? -ne 0 ]; then
-  echo -e "TypeScript compilation failed, aborting commit."
-  exit 1
-else
-  echo -e "TypeScript compilation completed successfully."
+TS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E  "\.tsx?$|\.ts$")
+
+if [ -n "$TS_FILES" ]; then
+  for FILE in $TS_FILES
+  do
+    ./node_modules/.bin/tsc --noEmit "$FILE"
+    if [ $? -ne 0 ]; then
+      echo -e "TypeScript compilation failed for $FILE, aborting commit."
+      exit 1
+    fi
+  done
 fi
 
-# Add back the modified/prettified files to staging
+echo -e "\nValidating JavaScript compilation:"
+JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.js$")
+
+if [ -n "$JS_FILES" ]; then
+  for FILE in $JS_FILES
+  do
+    node --check "$FILE"
+    if [ $? -ne 0 ]; then
+      echo -e "JavaScript compilation failed for $FILE, aborting commit."
+      exit 1
+    fi
+  done
+fi
+
+echo -e "\nValidating TSX compilation:"
+TSX_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.tsx?$")
+
+if [ -n "$TSX_FILES" ]; then
+  for FILE in $TSX_FILES
+  do
+    ./node_modules/.bin/tsc --noEmit "$FILE"
+    if [ $? -ne 0 ]; then
+      echo -e "TSX compilation failed for $FILE, aborting commit."
+      exit 1
+    fi
+  done
+fi
+
 echo "$FILES" | xargs git add
 echo "$STAGED_FILES" | xargs git add
 
