update pre-commit4

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,18 @@
 #!/bin/sh
+# npm test
 
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+# Get list of files staged for commit
+FILES=$(git diff-index --cached --name-only --diff-filter=ACM | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
+# Run Prettier on staged files
 echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-echo -e "\nValidating Javascript & Typescript with eslint:"
-
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
-
+# Validate JavaScript & TypeScript with ESLint
+STAGED_FILES=$(echo "$FILES" | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
 if [ -n "$STAGED_FILES" ]; then
   ESLINT_OUTPUT=$(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --format json)
-  
+
   if echo "$ESLINT_OUTPUT" | grep -q '"errorCount": [1-9]'; then
     echo -e "ESLint found errors, aborting commit."
     echo "$ESLINT_OUTPUT" | ./node_modules/.bin/eslint-formatter-friendly
@@ -21,48 +22,19 @@ if [ -n "$STAGED_FILES" ]; then
   fi
 fi
 
-echo -e "\nValidating TypeScript compilation:"
-TS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E  "\.tsx?$|\.ts$")
-
+# Validate TypeScript compilation and JavaScript syntax
+TS_FILES=$(echo "$STAGED_FILES" | grep -E "\.tsx?$|\.ts$|\.jsx?$|\.js$")
 if [ -n "$TS_FILES" ]; then
-  for FILE in $TS_FILES
-  do
-    ./node_modules/.bin/tsc --noEmit "$FILE"
-    if [ $? -ne 0 ]; then
-      echo -e "TypeScript compilation failed for $FILE, aborting commit."
-      exit 1
-    fi
-  done
+  ./node_modules/.bin/tsc --noEmit $TS_FILES
+  if [ $? -ne 0 ]; then
+    echo -e "JavaScript & TypeScript compilation failed, aborting commit."
+    exit 1
+  else
+    echo -e "JavaScript & TypeScript compilation completed successfully."
+  fi
 fi
 
-echo -e "\nValidating JavaScript compilation:"
-JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.js$")
-
-if [ -n "$JS_FILES" ]; then
-  for FILE in $JS_FILES
-  do
-    node --check "$FILE"
-    if [ $? -ne 0 ]; then
-      echo -e "JavaScript compilation failed for $FILE, aborting commit."
-      exit 1
-    fi
-  done
-fi
-
-echo -e "\nValidating TSX compilation:"
-TSX_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.tsx?$")
-
-if [ -n "$TSX_FILES" ]; then
-  for FILE in $TSX_FILES
-  do
-    ./node_modules/.bin/tsc --noEmit "$FILE"
-    if [ $? -ne 0 ]; then
-      echo -e "TSX compilation failed for $FILE, aborting commit."
-      exit 1
-    fi
-  done
-fi
-
+# Add back the modified/prettified files to staging
 echo "$FILES" | xargs git add
 echo "$STAGED_FILES" | xargs git add
 
