update pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,31 +1,28 @@
 #!/bin/sh
 
-# קבצים ששונו או נוספו וצריכים לעבור בדיקות (ACMR בלבד)
-FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -v 'node_modules/' | sed 's| |\\ |g')
+# Fetch all staged files that match the specified types
+FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
-# הפעלת Prettier על הקבצים ששונו או נוספו
+# Prettify all selected files
 echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-# בדיקת ESLint על קבצי JavaScript ו-TypeScript ששונו או נוספו
-echo -e "\nValidating Javascript & Typescript with eslint:"
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(jsx?|tsx?|js|ts)$')
+echo -e "\nValidating Javascript & Typescript with ESLint:"
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.jsx?$|\.tsx?$|\.js$|\.ts$")
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
 
+echo -e "ESLint validation completed."
 
-if [ -n "$STAGED_FILES" ]; then
-  ESLINT_OUTPUT=$(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --format json)
-  
-  if echo "$ESLINT_OUTPUT" | grep -q '"errorCount": [1-9]'; then
-    echo -e "ESLint found errors, aborting commit."
-    echo "$ESLINT_OUTPUT" | ./node_modules/.bin/eslint-formatter-friendly
-    exit 1
-  else
-    echo -e "ESLint validation completed successfully."
-  fi
+# Compile TypeScript files to check for errors
+echo -e "\nCompiling TypeScript files to check for errors:"
+./node_modules/.bin/tsc --noEmit
+tsc_result=$?
+if [ $tsc_result -ne 0 ]; then
+  echo "TypeScript compilation errors found. Aborting commit."
+  exit 1
 fi
 
-
-# הוספת הקבצים ששונו או נוספו מחדש ל-stage
+# Add back the modified/prettified files to staging
 echo "$FILES" | xargs git add
 echo "$STAGED_FILES" | xargs git add
 
