add husky config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,38 +1,30 @@
 #!/bin/sh
-
-# Fetch only modified staged files that match the specified types
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=M | grep "\.jsx\?$\|\.tsx\?$\|\.js$\|\.ts$")
-[ -z "$STAGED_FILES" ] && exit 0
+# npm test
+FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
+[ -z "$FILES" ] && exit 0
 
 # Prettify all selected files
-echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
+echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-echo -e "\nValidating Javascript & Typescript with ESLint:"
+echo -e "\nValidating Javascript & Typescript with eslint:"
+
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")
+
 echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix
 
-echo -e "ESLint validation completed."
+echo -e "Javascript & Typescript validation completed."
 
-# Generate a temporary tsconfig file for staged files
-TMP_TSCONFIG=$(mktemp)
-cat <<EOF > $TMP_TSCONFIG
-{
-  "include": [
-    $(echo "$STAGED_FILES" | sed 's|^|    "|;s|$|",|' | tr '\n' ' ')
-  ]
-}
-EOF
-
-# Compile only staged TypeScript files to check for errors
-echo -e "\nCompiling Javascript & Typescript files to check for errors:"
-./node_modules/.bin/tsc --noEmit --skipLibCheck -p $TMP_TSCONFIG
+# Compile all TypeScript files to check for errors
+echo -e "\nCompiling all Javascript & Typescript files to check for errors:"
+./node_modules/.bin/tsc --noEmit --skipLibCheck
 tsc_result=$?
-rm $TMP_TSCONFIG
 if [ $tsc_result -ne 0 ]; then
-  echo "Javascript & Typescript compilation errors found. Aborting commit."
+  echo "JavaScript & Typescript compilation errors found. Aborting commit."
   exit 1
 fi
 
 # Add back the modified/prettified files to staging
+echo "$FILES" | xargs git add
 echo "$STAGED_FILES" | xargs git add
 
-exit 0
+exit $?
